name: prova_pratica_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  mailer: ^6.4.1
  # path: ^1.8.0
mailer: ^6.4.1
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
